### ISSUE TITLE
Changing height of a UICollapsibleSection doesn't change content area size (causes troubles on mouseclicks)

### ISSUE THREAD

**Issue by dlopuch** [heronarts/P3LX#3]
Lets say you have a dynamically-sized `UICollapsibleSection` implementation (eg you swap in different images or control groups).

When you call `setHeight()` to resize it, I've noticed the mouseclick area doesn't adjust as well.  There's also some rendering glitches -- if you `setHeight()` to a smaller size, it looks like the content area overflows out past the new height (see bottomish-left side of this screenshot):
![screen shot 2017-06-29 at 5 10 33 pm](https://user-images.githubusercontent.com/1427329/27715740-0e89b0ce-5cee-11e7-803e-409e845c05a4.png)

Seems to be caused because `UICollapsibleSection` upon instantiation creates a `contentTarget` container, and this doesn't get adjusted on a `setHeight()` call.  

`UICollapsibleSection` should override setHeight() to change it's sublayout using same logic in the constructor.

**Comment by mcslee** [comment]
Hey Dan - there is a separate method called setContentHeight() which is what should be used when changing the content size of a UICollapsibleContainer:
https://github.com/heronarts/P3LX/blob/master/src/heronarts/p3lx/ui/UI2dContainer.java#L247

Note that the content target in UICollapsibleSection appropriately listens for changes to its size, and updates the height of its container appropriately:
https://github.com/heronarts/P3LX/blob/master/src/heronarts/p3lx/ui/studio/UICollapsibleSection.java#L75

I think overriding setHeight() will be likely to cause problems. For the use case you're describing, setContentHeight() is the appropriate UI method to call - I think you shouldn't have any problems if you call that method after changing your content size, instead of calling the top-level setHeight() method.

**Comment by dlopuch** [comment]
Yeah, that works. 

Might be worthwhile to add a quick note in the UICollapsibleSection javadoc like "Uses a dedicated contentTarget container to do the collapsing, use #setContentHeight and #setContentWidth for resizing operations" or something like that. 

Thanks!
