### ISSUE TITLE
UIToggleSet does not work with range DiscreteParameter objects

### ISSUE THREAD

**Issue by phil-levis** [heronarts/P3LX#9]
A UIToggle set assumes that a DiscreteParameter is configured with a `String[]` rather than a range. Configuring it with a range doesn't fill in the corresponding `String[]` of options and it is `null`. `UIToggleSet` assumes the presence of a `String[]` of options. As a result, if you try to create a `UIToggleSet` with a `DiscreteParameter` configured with a range, you get a `NullPointerException` when it ties to access the `String[]` of options. Example test code:

```
import heronarts.lx.parameter.DiscreteParameter;
import heronarts.p3lx.ui.component.UIToggleSet;

public class TestToggle {
    public static void main(String[] args) {
        DiscreteParameter param = new DiscreteParameter("Param", 1, 1, 7);
        UIToggleSet toggle = new UIToggleSet();
        toggle.setParameter(param);
    }
}
```

There are two possible fixes:

  1. Have two different `UIToggleSet` subclasses, one for integer ranges and one for `String[]`.
  2. Convert the range into a `String[]` automatically. The problem with this approach is it's one-way. A set initialized with strings does not have integer values, but a set initialized with integer values has strings.

The second is an easy bugfix; the first is conceptually cleaner and doesn't have subsequent (unfixable) bugs.

**Comment by mcslee** [comment]
Apologies this, sloppy mess left behind on my part, relic of my never personally using the UIToggleSet for raw integer parameters. One of the UI elements I have taken care of the least. But definitely a bug, the UIToggleSet ought to work without string options specified.

I think approach (2) is actually conceptually correct, as I think of the set initialized with Strings as implicitly having integer values - the options array is ordered, the indices of the Strings are their integer values.

The setValue(int) method on UIToggleSet will behave as expected, and those values will always correspond to the indices of the toggle-set (e.g. 0 - range). I've added comments to clarify this. Basically,  I think of the setValue() and getValue() methods on UIToggleSet as referring not to the underlying parameter, but referring to the UI control itself. A UIToggleSet control always displays an ordered list of N Strings to the user.

Also just FYI relating to your earlier setValue() question, I really discourage ever using the setValue() method of any of these UI controls. The existence of those methods as public at all is a bit of a relic from when I originally didn't want to strictly require that these UI controls use the underlying LXParameter system. When you are using LXParameters, in almost every situation you should call parameter.setValue(), rather than uiControlForParameter.setValue(). And you should use an LXParameterListener to observe the parameter itself for changes, not the UI control (the parameter's value could be changed by things other than the UI control).

Just in case you're not aware of it, the UIIntegerBox is often a better UI choice for raw integer parameter selection (or UIKnob also works reasonably with integers).

Fixed here: https://github.com/heronarts/P3LX/commit/3ef3f29c3dbcb7e85b0b19d387cd35d741f00099

**Comment by mcslee** [comment]
Merged into LXStudio-IDE:
https://github.com/heronarts/LXStudio-IDE/commit/6d4a33b7ecbbb4b1426450a36d21e313e1d69a5f

**Comment by phil-levis** [comment]
If the ToggleSet represents an enumeration of Strings (i.e., strings with associated integer identifiers), then I'd suggest you disambiguate labels and values. Part of the issue is it talks about Options and Values, or Values and Index intercheangably. E.g., setValue(String) should become setSelectedOption(String) and setValue(int) should become setSelectedIndex(int). But the key thing is it's an index, not a value in an arbitrary range. Alternatively, if you want it to be more flexible enumeration values, you should be able to provide an `int[]` for the values (which default to 0..len).

In my particular case, I'd rather have a small set of toggle-able options than an IntegerBox with small range. This particular control has to do with geometric placement of the lit elements: they can be hung on one of 6 I-beams, so I want 1-6. Having it be an integer field requires a mouse->keyboard-> mouse change, as opposed to just allowing mouse control. A quantized slider would also work, but that's not a provided component.

So in my case, I'll use a ToggleSet, where the Strings are just numbers.

**Comment by mcslee** [comment]
Yep - fully agreed with all these comments. I felt the same queasiness as I was documenting setValue(). Better to change these to avoid confusion.

Have done that here: https://github.com/heronarts/P3LX/commit/a05b16e1c8527151f6936117266d303882adbe24

Makes good sense on your UI use case as well.
